/**
 * Downloads every face in lib/fonts/registry.ts from Google Fonts (static TTF
 * instances) into assets/fonts/, then generates lib/fonts/next-fonts.ts.
 * Run once after changing the registry:  npm run fonts
 */
import { mkdir, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { FONT_FAMILIES, fontFile } from "../lib/fonts/registry";

const root = path.resolve(import.meta.dirname, "..");
const outDir = path.join(root, "assets/fonts");

async function exists(p: string) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  await mkdir(outDir, { recursive: true });
  for (const fam of FONT_FAMILIES) {
    for (const face of fam.faces) {
      const file = path.join(outDir, fontFile(fam, face));
      if (await exists(file)) continue;
      const ital = face.style === "italic" ? 1 : 0;
      const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(fam.family)}:ital,wght@${ital},${face.weight}`;
      // A non-browser user agent makes Google serve plain TTF instances.
      const css = await (await fetch(url, { headers: { "user-agent": "curl/8" } })).text();
      const m = css.match(/src:\s*url\(([^)]+\.ttf)\)/);
      if (!m) throw new Error(`No TTF for ${fam.family} ${face.weight} ${face.style}:\n${css}`);
      const buf = Buffer.from(await (await fetch(m[1])).arrayBuffer());
      await writeFile(file, buf);
      console.log(`  ${fontFile(fam, face)}  ${(buf.length / 1024).toFixed(0)} KB`);
    }
  }

  // next/font/local needs literal options at module scope, so generate them.
  const lines = [
    "// AUTO-GENERATED by scripts/fetch-fonts.ts. Do not edit by hand.",
    'import localFont from "next/font/local";',
    "",
  ];
  const entries: string[] = [];
  for (const fam of FONT_FAMILIES) {
    const id = "f_" + fam.slug.replace(/-/g, "_");
    const src = fam.faces
      .map((face) => `    { path: "../../assets/fonts/${fontFile(fam, face)}", weight: "${face.weight}", style: "${face.style}" },`)
      .join("\n");
    lines.push(`const ${id} = localFont({\n  src: [\n${src}\n  ],\n  display: "block",\n  adjustFontFallback: false,\n  preload: false,\n});`);
    entries.push(`  ${JSON.stringify(fam.family)}: ${id},`);
  }
  lines.push("", "/** Canonical family name -> next/font result (className + style.fontFamily). */");
  lines.push(`export const NEXT_FONTS = {\n${entries.join("\n")}\n} as const;`, "");
  await writeFile(path.join(root, "lib/fonts/next-fonts.ts"), lines.join("\n"));
  console.log("Generated lib/fonts/next-fonts.ts");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
