// AUTO-GENERATED by scripts/fetch-fonts.ts. Do not edit by hand.
import localFont from "next/font/local";

const f_fraunces = localFont({
  src: [
    { path: "../../assets/fonts/fraunces-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/fraunces-400i.ttf", weight: "400", style: "italic" },
    { path: "../../assets/fonts/fraunces-600.ttf", weight: "600", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_instrument_serif = localFont({
  src: [
    { path: "../../assets/fonts/instrument-serif-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/instrument-serif-400i.ttf", weight: "400", style: "italic" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_cormorant_garamond = localFont({
  src: [
    { path: "../../assets/fonts/cormorant-garamond-500.ttf", weight: "500", style: "normal" },
    { path: "../../assets/fonts/cormorant-garamond-500i.ttf", weight: "500", style: "italic" },
    { path: "../../assets/fonts/cormorant-garamond-600.ttf", weight: "600", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_eb_garamond = localFont({
  src: [
    { path: "../../assets/fonts/eb-garamond-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/eb-garamond-400i.ttf", weight: "400", style: "italic" },
    { path: "../../assets/fonts/eb-garamond-600.ttf", weight: "600", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_newsreader = localFont({
  src: [
    { path: "../../assets/fonts/newsreader-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/newsreader-400i.ttf", weight: "400", style: "italic" },
    { path: "../../assets/fonts/newsreader-600.ttf", weight: "600", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_playfair_display = localFont({
  src: [
    { path: "../../assets/fonts/playfair-display-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/playfair-display-400i.ttf", weight: "400", style: "italic" },
    { path: "../../assets/fonts/playfair-display-700.ttf", weight: "700", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_dm_serif_display = localFont({
  src: [
    { path: "../../assets/fonts/dm-serif-display-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/dm-serif-display-400i.ttf", weight: "400", style: "italic" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_libre_caslon_text = localFont({
  src: [
    { path: "../../assets/fonts/libre-caslon-text-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/libre-caslon-text-400i.ttf", weight: "400", style: "italic" },
    { path: "../../assets/fonts/libre-caslon-text-700.ttf", weight: "700", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_spectral = localFont({
  src: [
    { path: "../../assets/fonts/spectral-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/spectral-400i.ttf", weight: "400", style: "italic" },
    { path: "../../assets/fonts/spectral-600.ttf", weight: "600", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_ibm_plex_serif = localFont({
  src: [
    { path: "../../assets/fonts/ibm-plex-serif-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/ibm-plex-serif-400i.ttf", weight: "400", style: "italic" },
    { path: "../../assets/fonts/ibm-plex-serif-600.ttf", weight: "600", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_space_grotesk = localFont({
  src: [
    { path: "../../assets/fonts/space-grotesk-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/space-grotesk-500.ttf", weight: "500", style: "normal" },
    { path: "../../assets/fonts/space-grotesk-700.ttf", weight: "700", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_bebas_neue = localFont({
  src: [
    { path: "../../assets/fonts/bebas-neue-400.ttf", weight: "400", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_syne = localFont({
  src: [
    { path: "../../assets/fonts/syne-500.ttf", weight: "500", style: "normal" },
    { path: "../../assets/fonts/syne-700.ttf", weight: "700", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_inter = localFont({
  src: [
    { path: "../../assets/fonts/inter-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/inter-500.ttf", weight: "500", style: "normal" },
    { path: "../../assets/fonts/inter-600.ttf", weight: "600", style: "normal" },
    { path: "../../assets/fonts/inter-700.ttf", weight: "700", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_work_sans = localFont({
  src: [
    { path: "../../assets/fonts/work-sans-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/work-sans-500.ttf", weight: "500", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_ibm_plex_sans = localFont({
  src: [
    { path: "../../assets/fonts/ibm-plex-sans-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/ibm-plex-sans-500.ttf", weight: "500", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_inter_tight = localFont({
  src: [
    { path: "../../assets/fonts/inter-tight-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/inter-tight-500.ttf", weight: "500", style: "normal" },
    { path: "../../assets/fonts/inter-tight-600.ttf", weight: "600", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_source_sans_3 = localFont({
  src: [
    { path: "../../assets/fonts/source-sans-3-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/source-sans-3-600.ttf", weight: "600", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_dm_sans = localFont({
  src: [
    { path: "../../assets/fonts/dm-sans-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/dm-sans-500.ttf", weight: "500", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_karla = localFont({
  src: [
    { path: "../../assets/fonts/karla-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/karla-500.ttf", weight: "500", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_manrope = localFont({
  src: [
    { path: "../../assets/fonts/manrope-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/manrope-500.ttf", weight: "500", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_space_mono = localFont({
  src: [
    { path: "../../assets/fonts/space-mono-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/space-mono-700.ttf", weight: "700", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_ibm_plex_mono = localFont({
  src: [
    { path: "../../assets/fonts/ibm-plex-mono-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/ibm-plex-mono-500.ttf", weight: "500", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_jetbrains_mono = localFont({
  src: [
    { path: "../../assets/fonts/jetbrains-mono-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/jetbrains-mono-600.ttf", weight: "600", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});
const f_gentium_book_plus = localFont({
  src: [
    { path: "../../assets/fonts/gentium-book-plus-400.ttf", weight: "400", style: "normal" },
    { path: "../../assets/fonts/gentium-book-plus-400i.ttf", weight: "400", style: "italic" },
    { path: "../../assets/fonts/gentium-book-plus-700.ttf", weight: "700", style: "normal" },
  ],
  display: "block",
  adjustFontFallback: false,
  preload: false,
});

/** Canonical family name -> next/font result (className + style.fontFamily). */
export const NEXT_FONTS = {
  "Fraunces": f_fraunces,
  "Instrument Serif": f_instrument_serif,
  "Cormorant Garamond": f_cormorant_garamond,
  "EB Garamond": f_eb_garamond,
  "Newsreader": f_newsreader,
  "Playfair Display": f_playfair_display,
  "DM Serif Display": f_dm_serif_display,
  "Libre Caslon Text": f_libre_caslon_text,
  "Spectral": f_spectral,
  "IBM Plex Serif": f_ibm_plex_serif,
  "Space Grotesk": f_space_grotesk,
  "Bebas Neue": f_bebas_neue,
  "Syne": f_syne,
  "Inter": f_inter,
  "Work Sans": f_work_sans,
  "IBM Plex Sans": f_ibm_plex_sans,
  "Inter Tight": f_inter_tight,
  "Source Sans 3": f_source_sans_3,
  "DM Sans": f_dm_sans,
  "Karla": f_karla,
  "Manrope": f_manrope,
  "Space Mono": f_space_mono,
  "IBM Plex Mono": f_ibm_plex_mono,
  "JetBrains Mono": f_jetbrains_mono,
  "Gentium Book Plus": f_gentium_book_plus,
} as const;
